### ISSUE TITLE
Output for data/intermediate/KBP/em/type.txt is strange

### ISSUE THREAD

**Issue by Henderake** [shanzhenren/CoType#2]
The content of intermediate/KBP/em/type.txt is strange for the KBP corpus. I haven't tested on other corpora.

type.txt:
```
/       0       466411
p       1       177541
e       2       270192
r       3       288178
s       4       182380
o       5       480385
n       6       380277
l       7       159181
d       8       28569
i       9       303219
,       10      170403
m       11      42962
a       12      236368
c       13      196298
h       14      38605
t       15      312620
u       16      59252
g       17      59662
z       18      16877
_       19      16360
w       20      5846
k       21      2778
f       22      3852
y       23      52196
b       24      4285
v       25      21442
x       26      1
```

For relation mentions, type.txt looks fine:
```
None    0       111343
per:country_of_death    1       10265
per:country_of_birth    2       12040
per:parents     3       6984
per:children    4       6984
per:religion    5       2584
per:countries_of_residence      6       1
```

I believe the problem is caused by [ner_feature.py](https://github.com/shanzhenren/CoType/blob/master/code/DataProcessor/ner_feature.py#L84-L91) line 84 to line 91. For relation mention, **_mention.labels_** is a list so the code works ok. However, in the case of entity mention, **_mention.labels_** is a string (e.g. **_\/person\/soldier,\/person\/actor,\/person\/politician,\/person\/author,\/person_**) and the **_for_** loop will loop over the characters in the string and thus creating weird type.txt.

**Comment by ellenmellon** [comment]
Hi, thanks for raising the problem. It seems to be from a recent commit of nlp_parse.py. The issue should be fixed now.
