### ISSUE TITLE
Does CoType handle multiple relations between two entities in distant supervision?

### ISSUE THREAD

**Issue by Henderake** [shanzhenren/CoType#3]
I'm currently applying CoType for Freebase relation extraction. Between two entity mentions in a sentence, there might exists multiple relations between both entities. For example, there exists two relations **president_of** and **nationality** between **Obama** and **USA**.

In [distantSupervision.py of StructMineDataPipeline](https://github.com/shanzhenren/StructMineDataPipeline/blob/master/code/distantSupervision.py#L96), multiple relations are joined with commas (line 96). In my case, I select 100 relations as my target relations, but after feature generation, **intermediate/my_extraction/rm/type.txt** contains 1200 types, where multiple relations are seen as a type (**president_of,nationality** is one of the types) I wonder if CoType handles the case of multiple relations?

**Comment by ellenmellon** [comment]
Yes, we support multiple labels. The issue should be fixed now. Could you please try running CoType again? You don't have to rerun the data pipeline.

In our CoType datasets, we separate each multi-label relation mention into multiple single-label relation mentions. However, in our data pipeline, we made it more general to put all labels in a single relation mention and unfortunately, forgot to adapt the previous CoType code to it. Thanks for bringing up our attention!

**Comment by Henderake** [comment]
Thanks for all the support!

**Comment by shanzhenren** [comment]
Hi Ellen,

Please make sure other tools (PLE and AFET) can also adapt to the changes of data pipeline. Also, if you change the JSON reader in these tools, will the JSON input files given on the GitHub still be readable?

Regards,
Xiang Ren


On Jun 21, 2017, at 2:01 AM, Shyh-Horng Yeh <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for all the support!

**Comment by ellenmellon** [comment]
Yes, the provided JSON files are still adaptable. I will adjust PLE & AFET code as well.
