### ISSUE TITLE
The dataset linked to google drive seems to be wrong

### ISSUE THREAD

**Issue by Hunter-Lin** [shanzhenren/CoType#4]
I scanned through the test set of both NYT and KBP as referred to in the link. The 'test.json' in KBP have a field 'articleID' beginning with 'NYT', which suggests it might be the dataset from NYT.

Hope to update the correct dataset links in google drive :)

**Comment by shanzhenren** [comment]
I believe the test.json file is correct. Those articles ID are just for indicating source of the document. KBP’s test set consists of articles from NYT, APW, etc. (different news agencies).

Xiang

**Comment by happylicio** [comment]
In NYT train.json, I found that the triplets with "None "relation label are up to 261243, so very few samples I could use to train my model. Do you only use these 30K+ samples too? 
![image](https://user-images.githubusercontent.com/18717873/31612093-302495c2-b244-11e7-86e4-0a8f9a8e3dac.png)

**Comment by shanzhenren** [comment]
That’s actually the case in train.json — # of None instances is roughly 3x the # of positive instances since we sample the none labels by 3x.

Xiang
