### ISSUE TITLE
liblinear.so.3

### ISSUE THREAD

**Issue by zhaoluffy** [shanzhenren/CoType#5]
During Evaluate on Relattion Extraction, "raise Exception('LIBLINEAR library not found.')" and I don't use try 
 it report "OSError: ~/anaconda2/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /data/guozhao/sourceCodes/CoType-master/code/Classifier/liblinear.so.3)".

**Comment by shanzhenren** [comment]
This is probably the incorrect setup/installment of Liblinear package (https://www.csie.ntu.edu.tw/~cjlin/liblinear/) when you are running the logistic regression baseline.

**Comment by zhaoluffy** [comment]
Thank you very much, now codes run well.
