### ISSUE TITLE
Missing descriptions for the output files of retype

### ISSUE THREAD

**Issue by minseven** [shanzhenren/CoType#6]
Hi, 

I am very interested in how CoType works. However, it seems I can't find any descriptions for the output files generated from retype. More specifically, when I did test run with KBP, it gives the following outputs:

data/results/KBP/em:
total 309M
-rw-rw-r-- 1 msk msk 240M Nov 30 12:34 emb_retype_feature.txt
-rw-rw-r-- 1 msk msk  70M Nov 30 12:34 emb_retype_mention.txt
-rw-rw-r-- 1 msk msk  62K Nov 30 12:34 emb_retype_type.txt

data/results/KBP/rm:
total 440M
-rw-rw-r-- 1 msk msk 368M Nov 30 12:35 emb_retype_feature.txt
-rw-rw-r-- 1 msk msk  73M Nov 30 12:34 emb_retype_mention.txt
-rw-rw-r-- 1 msk msk 3.4K Nov 30 12:35 emb_retype_type.txt
-rw-rw-r-- 1 msk msk  48K Nov 30 12:35 prediction_emb_retype_cosine.txt
-rw-rw-r-- 1 msk msk 2.8K Nov 30 12:35 tune_thresholds_emb_retype_cosine.txt

However, I don't understand what each file means and what rows/columns of each file represent. Can you please provide this information?

Thank you,
Minseung Kim

**Comment by shanzhenren** [comment]
@ellenmellon could you help add the description for these files?

**Comment by ellenmellon** [comment]
Hi Minseung,

The files that starts with "emb_retype_" contains the embedding information of nodes (feature, mention or type). Each line prints node_name, node_id and embedding vector in order. They are separated by tabs. The embedding vector are numerical numbers separated by spaces. "prediction_emb_retype_cosine.txt" contains predicted labels as well as the confidence score. Each line contains mention_id, predicted_label_id (most confident label) and confidence score in order. "tune_thresholds_emb_retype_cosine.txt" gives information on the performance given difference cutoff scores. Hope this helps.
