### ISSUE TITLE
Regarding fields of train.json

### ISSUE THREAD

**Issue by aditya-shekhar** [shanzhenren/CoType#7]
Are the parameters sentId and start (inside entityMentions) used in the training / testing ?

**Comment by shanzhenren** [comment]
No. They are used for feature generation step.

Regards,
Xiang Ren

**Comment by aditya-shekhar** [comment]
Thanks Xiang, 

Basically, we are trying to generate the result on a different datasets which we have created using freebase. In our dataset we have sentences, entity classified and the all possible relation between those pair of enities, but we don't have any sentId and start. Can you please let me know the signifince/meaning of "start" and "sentId" in your dataset. So that we can generate the results.
Thanks
Aditya

**Comment by aditya-shekhar** [comment]
```
{"sentText": "Evaluation of children for cervical spine injuries ( CSIs ) after blunt trauma is complicated , particularly if the patient is unresponsive because of severe traumatic brain injury}
```
```
{"start": 25, "text": "cervical spine", "label": "base.type_ontology.physically_instantiable,base.type_ontology.non_agent,medicine.anatomical_structure"}, {"start": 26, "text": "Evaluation", "label": "organization.organization_sector"}, {"start": 33, "text": "CSIs", "label": "base.type_ontology.abstract,base.type_ontology.inanimate,organization.organization,government.government_agency,base.type_ontology.agent"},

```

**Comment by ellenmellon** [comment]
Hi Aditya,

"start" should be the order of the entity mention appearance in the
sentence. For example, in a sentence "A ... B ... C ...", entity mention A
should have "start" 0 and B should have "start" 1. But it seems like
eventually this "start" information is not used. Thus, you may simply
ignore it. Let me know if you encounter any problem by removing this entry.

"sentId" is how you differentiate sentences with the same "article id".
Just make sure for each sentence with the same article id, you have a
unique sentence id.

Hope this helps.

Thanks,
Ellen

**Comment by aditya-shekhar** [comment]
Thanks Ellen
